---
title: "Regresores endógenos: errores de medida y/o simulteneidad en las variables del modelo de regresión"
author: "Julián Ramajo"
date: "1/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Lectura de librerías
library(tidyverse)
library(ivreg)
library(momentfit)
# Para más detalles sobre el método de variables instrumentales (IV o 2SLS en inglés) ver las páginas web: 
# https://cran.r-project.org/web/packages/ivreg/vignettes/ivreg.html 
# https://cran.r-project.org/web/packages/ivreg/vignettes/Diagnostics-for-2SLS-Regression.html
#
# Lectura de datos
INF_INT <- read_csv("INF_INTERN.csv")
summary(INF_INT)
# Estimación MCO
modelo_MCO <- lm(INF ~ RM + RY, data=INF_INT)
summary(modelo_MCO)
# Estimación VI
modelo_IV <- ivreg(INF ~ RM + RY | RM + EDUC + INV + RPOB + YPC0, data=INF_INT)
summary(modelo_IV, diagnostics=TRUE)
# Comparación de modelos
car::compareCoefs(modelo_MCO, modelo_IV)
#
library("modelsummary")
model_list <- list(OLS = modelo_MCO, IV = modelo_IV)
msummary(model_list)
modelplot(model_list)
#
# Generalización del método de variables instrumentales (IV): método generalizado de los momentos (GMM)
# Para más detalles sobre el GMM ver las páginas web:
# https://cran.r-project.org/web/packages/gmm/vignettes/gmm_with_R.pdf
# https://cran.r-project.org/web/packages/momentfit/vignettes/gmmS4.pdf
#
modelo_GMM <- momentModel(INF ~ RM + RY, ~ RM + EDUC + INV + RPOB + YPC0, data=INF_INT, vcov="iid") #  vcov="MDS" HC0 (heter) ;  vcov="HAC" (heter + autocorr);  vcov="CL" (cluster)
modelo_GMM
res_modelo_GMM <- gmmFit(modelo_GMM)
summary(res_modelo_GMM)
DWH(res_modelo_GMM)
```

```{python}
# Lectura de librerías
import pandas as pd
import numpy as np
import statsmodels.api as sm
from linearmodels.iv import IV2SLS
from linearmodels.iv import IVGMM
# import statsmodels.stats.api as sms
# import statsmodels.formula.api as smf
# import scipy as sp
# import scipy.stats as scs
# import matplotlib.pyplot as plt
# import seaborn as sns
#
# Lectura de datos
INF_INT = pd.read_csv('INF_INTERN.csv')
INF_INT.describe()
#
INF_INT = sm.add_constant(INF_INT)
# Estimación MCO
modelo_MCO = IV2SLS(dependent = INF_INT.INF,
               exog = INF_INT[['const','RM','RY']], 
               endog = None, 
               instruments = None)
res_modelo_MCO = modelo_MCO.fit(cov_type='unadjusted')
print(res_modelo_MCO)
# Estimación IV(2SLS)
modelo_IV = IV2SLS(dependent = INF_INT.INF,
               exog = INF_INT[['const','RM']],
               endog = INF_INT.RY,
               instruments = INF_INT[['EDUC','INV','RPOB','YPC0']])
res_modelo_IV = modelo_IV.fit(cov_type='unadjusted')
print(res_modelo_IV)
res_modelo_IV.wu_hausman()
# Estimación GMM
modelo_GMM = IVGMM(dependent = INF_INT.INF,
               exog = INF_INT[['const','RM']],
               endog = INF_INT.RY,
               instruments = INF_INT[['EDUC','INV','RPOB','YPC0']])
res_modelo_GMM = modelo_GMM.fit(cov_type='unadjusted')
print(res_modelo_GMM)
# Comparación de resultados
from collections import OrderedDict
from linearmodels.iv.results import compare
res_modelos = OrderedDict()
res_modelos["MCO"] = res_modelo_MCO
res_modelos["IV"] = res_modelo_IV
res_modelos["GMM"] = res_modelo_GMM
print(compare(res_modelos))
```

