---
title: 'TEMA 3: Estabilidad de los parámetros estructurales (código R)'
author:
  name: Julián Ramajo, ramajo@unex.es
  affiliation: GRADO EN ESTADÍSTICA | ECONOMETRIA (502243)
subtitle: 'Aplicaciones 3.2: Exportaciones españolas. Diferenciación salarial por sexo. Gasto en construcción. Consumo de electricidad'
output:
  html_document:
    theme: journal
    highlight: haddock
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

# Objetivo

En esta aplicación se estimarán varias regresiones que permiten parámetros no constantes.

# Exportaciones españolas

```{r, message=FALSE}
# Lectura de librerías
library(tidyverse)
library(car)
# Lectura de datos
EXP_ESP <- read_csv("EXP_ESP_Y.csv")
# Dvisión de la muestra preUE (1970-1985) y postUE (1986-1997)
Y1986=match(1986,EXP_ESP$obs)
Y1986
#
UE <- factor(c(rep(0, 16), rep(1, 12)), labels=c("preUE", "postUE"))
UE
class(UE)
#
EXP_ESP$D1986 <- as.numeric(UE)-1
EXP_ESP$D1986
class(EXP_ESP$D1986)
#
EXP_ESP_ts <- ts(EXP_ESP[,2:5], start=c(1970), end = c(1997), frequency = 1)
plot(EXP_ESP_ts)
#
# Ecuación de exportaciones (1970-1997)
#
lm_X_ESP <- lm(log(XGS) ~ log(WGDP) + log(REER), data = EXP_ESP_ts)
summary(lm_X_ESP)
#
scatterplot(log(XGS) ~ log(WGDP)| D1986, data=EXP_ESP_ts, smooth=FALSE, boxplots=FALSE, 
            ylab="Relación parcial Exportaciones/PIB mundial (logs)")
scatterplot(log(XGS) ~ log(REER)| D1986, data=EXP_ESP_ts, smooth=FALSE, boxplots=FALSE, 
            ylab="Relación parcial Exportaciones/Tipo de cambio (logs)")
#
# ¿Existe diferenciación por períodos?
#
# Test de Chow de cambio estructural
#
#  Cálculo manual
#
summary(lm_X_ESP)
SRCT <- sum(residuals(lm_X_ESP)^2)
SRCT
T <- nobs(lm_X_ESP)
T
K <- T -df.residual(lm_X_ESP)
K
# PreUE
preUE <- window(EXP_ESP_ts, start=1970, end = 1985)
lm_X_ESP_preUE <- lm(log(XGS) ~ log(WGDP) + log(REER) , data = preUE)
summary(lm_X_ESP_preUE)
SRC1 <- sum(residuals(lm_X_ESP_preUE)^2)
SRC1
T1 <- nobs(lm_X_ESP_preUE)
T1
# PostUE
postUE <- window(EXP_ESP_ts, start=1986, end = 1997)
lm_X_ESP_postUE <- lm(log(XGS) ~ log(WGDP) + log(REER) , data = postUE)
summary(lm_X_ESP_postUE)
SRC2 <- sum(residuals(lm_X_ESP_postUE)^2)
SRC2
T2 <- nobs(lm_X_ESP_postUE)
T2
#
CHOW=((SRCT-(SRC1+SRC2))/K)/((SRC1+SRC2)/(T-2*K))
CHOW
pval <-  1-pf(CHOW,K,(T-2*K))
pval
# Comparación de parámetros
compareCoefs(lm_X_ESP_preUE,lm_X_ESP_postUE)
#
# Cálculo automático
#
# Método 1 (ANOVA)
summary(lm_X_EXP_int <- lm(log(XGS) ~ log(WGDP) + log(REER) + D1986/(log(WGDP) + log(REER)), data = EXP_ESP_ts))
anova(lm_X_ESP, lm_X_EXP_int)
# Método 2 (librería structchange)
library(strucchange)
sctest(log(XGS) ~ log(WGDP) + log(REER), data=EXP_ESP_ts, type = "Chow", point = Y1986-1)
#
# Contrastes tipo Chow basados en estimaciones recursivas
# 
sbtest <- Fstats(log(XGS) ~ log(WGDP) + log(REER), data = EXP_ESP_ts, from = 0.15, to = 0.85)
sbtest[["Fstats"]]
# Gráfica de los estadísticos F 
plot(sbtest, alpha = 0.05)
# Gráfica de los correspondientes P-valores
plot(sbtest, pval = TRUE, alpha = 0.05)
# Test de Chow (1960) [versión Chi2]
Chow_F <- sbtest$Fstats[Y1986-4] # Punto de ruptura: 17 - 4 (15% suprimidos a la izquierda)
Chow_F # Se puede comprobar que Chow_F/K=CHOW
# Chow_F tiene una distribución asintótica Chi^2 mientras Chow_F/K tiene una distribución exacta F_K,T-2*K
pval <-  1-pchisq(Chow_F,sbtest$nreg) 
pval
#
# Contrastes de Andrews (1993) y Andrews y Ploberger (1994) [punto de ruptura desconocido]
#
sctest(sbtest, type = "supF")
sctest(sbtest, type = "aveF")
sctest(sbtest, type = "expF")
#
# Test CUSUM (Brown, Durbin y Evans, 1975)
plot(efp(log(XGS) ~ log(WGDP) + log(REER), data = EXP_ESP_ts))
#
# Regresión diferenciada por tramos
#
summary(lm(log(XGS) ~ (log(WGDP) + log(REER))*D1986, data=EXP_ESP_ts))
# Versión alternativa
summary(lm(log(XGS) ~ (log(WGDP) + log(REER))*UE, data=EXP_ESP_ts))
#
compareCoefs(lm_X_ESP_preUE,lm_X_ESP_postUE)
#
```

# Diferencias salariales por sexo

```{r, message=FALSE}
# Lectura de librerías
library(tidyverse)
library(car)
# Lectura de datos
SAL_SEX <- read_csv("SAL_SEX.csv")
#
Boxplot(~SALARIO, data=SAL_SEX, main="", ylab="SALARIO", id=list(method = "none"))
#
class(SAL_SEX$MUJER)
SEXO <- factor(SAL_SEX$MUJER, labels=c("Hombre", "Mujer"))
summary(SEXO)
Boxplot(SALARIO~SEXO, data=SAL_SEX, ylab="SALARIO", id=list(method = "none"))
#
# Ecuación de salarios
#
summary(lm_SAL <- lm(log(SALARIO) ~ EDUC + EXPER , data = SAL_SEX))
#
scatterplot(log(SALARIO) ~ EDUC| SEXO, data=SAL_SEX, smooth=FALSE, boxplots=FALSE, ylab="Relación parcial log(Salario)/Educación")
scatterplot(log(SALARIO) ~ EXPER| SEXO, data=SAL_SEX, smooth=FALSE, boxplots=FALSE, ylab="Relación parcial log(Salario)/Experiencia")
# 
# ¿Existe diferenciación por sexos?
#
SAL_SEX_h <- SAL_SEX[which(SAL_SEX$MUJER==0),] # datos hombres
SAL_SEX_m <- SAL_SEX[which(SAL_SEX$MUJER==1),] # datos mujeres
#
summary(lm_SAL_h <- lm(log(SALARIO) ~ EDUC + EXPER , data = SAL_SEX_h))
summary(lm_SAL_m <- lm(log(SALARIO) ~ EDUC + EXPER , data = SAL_SEX_m))
#
compareCoefs(lm_SAL_h, lm_SAL_m)
#
# Test de Chow
summary(lm_SAL_int <- lm(log(SALARIO) ~ EDUC + EXPER + MUJER/(EDUC + EXPER), data = SAL_SEX))
anova(lm_SAL, lm_SAL_int)
#
# Regresión diferenciada por sexos
#
summary(lm_SAL_int <- lm(log(SALARIO) ~ (EDUC + EXPER)*MUJER, data = SAL_SEX))
#
compareCoefs(lm_SAL_h, lm_SAL_m)
#
```

# Inversión en construcción en Estados Unidos

```{r, message=FALSE}
# Lectura de librerías
library(tidyverse)
library(plotly)
# Lectura de datos: y = Total Construction Spending (TTLCON) [ https://fred.stlouisfed.org/series/TTLCON) ]
TCS <- read_csv("TTLCON_USA.csv") %>% setNames(c("date","y"))
head(TCS)
tail(TCS)
class(TCS)
str(TCS)
# Gráfica de los datos
plot_ly(data = TCS) %>% add_lines(x = ~ date, y = ~ y)
# Construcción de tendencias
TCS <- TCS %>%
  mutate(seg1 = 1:nrow(TCS),
         seg2 = pmax(0, seg1 - min(seg1[seg1[which(date > as.Date("2007-08-01"))]])),
         seg3 = pmax(0, seg1 - min(seg1[seg1[which(date > as.Date("2011-01-01"))]])))
# Modelo con tendencia simple
mod1 <- lm(y ~ seg1, data = TCS)
summary(mod1)
# Modelo con tendencias sementadas (con pivote conocido)
mod2 <- lm(y ~ seg1 + seg2 + seg3, data = TCS)
summary(mod2)
TCS$yhat1 <- predict(mod1)
TCS$yhat2 <- predict(mod2)
# Gráfica de los datos con las tendencias ajustadas por los dos modelos
plot_ly(data = TCS) %>%
  add_markers(x = ~ date,
              y = ~ y,
              marker = list(
                opacity = 0.6,
                color = "#90e0ef",
                size = 8),
              name = "Gasto en construcción") %>%
add_lines(x = ~ date,
          y = ~ yhat1,
          line = list(color = "red",
                      dash = "dash",
                      width = 4),
          name = "Tendencia simple") %>%
  add_lines(x = ~ date,
            y = ~ yhat2,
            line = list(color = "#fca311",
                        dash = "dot",
                        width = 6),
            name = "Tendencia segmentada") %>%
  layout(title = "Gasto total en construcción en USA",
         font = list(color = "black"),
         yaxis = list(title = "Millones de dólares"),
         xaxis = list(title = "Fuente: U.S. Census Bureau, Total Construction Spending, extraído de FRED (fred.stlouisfed.org)"),
         margin = list(t = 50, b = 80),
         legend = list(x = 0.05, y = 0.95))
#
```

# Consumo de electricidad

```{r, message=FALSE}
# Lectura de librerías
library(alr4)
# Datos
help(segreg)
head(segreg)
tail(segreg)
#
plot(C ~ Temp, segreg, xlab="Temperatura media del mes (ºF)", ylab="Consumo de electricidad (KWH/día)")
#
# Modelo lineal con tendencia simple
lin.reg <- lm(C ~ Temp, data=segreg)
summary(lin.reg)
#
plot(C ~ Temp, segreg, xlab="Temperatura media (ºF)", ylab="Consumo de electricidad (KWH/día)")
x <- (0:90)
lines(x, predict(lin.reg, data.frame(Temp=x)))
# Modelo no lineal con tendencia segmentada
segm.reg <- nls(C ~ th0 + th1 * (pmax(0, Temp - gamma)), data=segreg, start=list(th0=70, th1=.5, gamma=40))
summary(segm.reg)
#
plot(C ~ Temp, segreg, xlab="Temperatura media (ºF)", ylab="Consumo de electricidad (KWH/día)")
x <- (0:90)
lines(x, predict(segm.reg, data.frame(Temp=x)))
# Bootstrapping del modelo
segm.reg.boot <- Boot(segm.reg, R=999)
summary(segm.reg.boot)
confint(segm.reg.boot)
hist(segm.reg.boot, layout=c(1, 3))
#
```
