---
title: 'Variable dependiente limitada. Truncamiento selectivo: el Modelo Heckit de selección muestral'
author:
  name: Julián Ramajo, ramajo@unex.es
  affiliation: GRADO EN ESTADÍSTICA | ECONOMETRIA (502243)
subtitle: 'Aplicación 3.14: Salarios de las mujeres casadas en el Reino Unido'
output:
  html_document:
    theme: journal
    highlight: haddock
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

# Objetivo

En esta aplicación se estima una ecuación Minceriana de salarios para las mujeres casadas basada en una investigación de Thomas A. Mroz del año 1987 para UK. El modelo propuesto es el siguiente:
$$log(SALARIO_{i}) = \beta_1 + \beta_2 EDUC_{i} + \beta_3 EXPER_{i} + e_{i}$$
donde SALARIO representa el salario por hora trabajada observado, EDUC el nivel de educación y EXPER el nivel de experiencia.
Al realizar una encuesta a una muestra de N = 753 mujeres casadas, representativa de la población femenina con ese estado civil en UK, preguntándoles entre otras cosas por su salario, muchas de ellas (325 mujeres) respondieron que esa cuestión no era relevante en su caso, ya que eran “amas de casa” (población no activa) y no recibían remuneración alguna por ese trabajo. Solo se observaron datos sobre salarios de mercado para aquellas mujeres (n = 428) que participaban en la fuerza de trabajo.

# Cógigo R

```{r, message=FALSE}
# Lectura de librerías
library(tidyverse)
library(sampleSelection) # http://www.sampleselection.org/
# Lectura de datos
SAL_MUJ <- read_csv("SAL_MUJ.csv")
summary(SAL_MUJ)
# Modelo Heckit (https://cran.r-project.org/web/packages/sampleSelection/vignettes/selection.pdf)
modelo_heckit <- selection(PMT ~ EDUC + EDAD + HIJOSMEN + TMIMP, log(SALARIO) ~ EDUC + EXPER, data=SAL_MUJ, method="ml")
summary(modelo_heckit)
```

# Código Python

```{python, message=FALSE}
# Lectura de librerías
import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
# Lectura de datos
SAL_MUJ = pd.read_csv("SAL_MUJ.csv")
SAL_MUJ.describe()
# Modelo Heckit
# Estimación en dos pasos (menos eficiente que la estimación ML)
# Realizando las regresiones "manualmente"
# Paso 1 (modelo Probit para todas las observaciones)
reg_probit = smf.probit(formula='PMT ~ EDUC + EDAD + HIJOSMEN + TMIMP', data=SAL_MUJ)
res_probit = reg_probit.fit(disp=0)
print(res_probit.summary())
#
pred_PMT = res_probit.fittedvalues
SAL_MUJ['inv_mills'] = stats.norm.pdf(pred_PMT) / stats.norm.cdf(pred_PMT)
# Paso 2 (regresión truncada con las observaciones seleccionadas y la inversa de la razón de Mills como variable explicativa adicional)
reg_heckit = smf.ols(formula='np.log(SALARIO) ~ EDUC + EXPER + inv_mills', subset=(SAL_MUJ['PMT'] == 1), data=SAL_MUJ).fit(cov_type='HAC', cov_kwds={'maxlags':6,'use_correction':True})
print(reg_heckit.summary())
# Usando el script heckman.py (statsmodels): errores estándar correctos
SAL_MUJ['lSALARIO'] = np.log(SAL_MUJ['SALARIO'])
lSALARIO = SAL_MUJ['lSALARIO'].copy() # Variable dependiente regresión truncada
Xs = SAL_MUJ[['EDUC', 'EXPER']] # Variables exógenas regresión truncada
X = sm.add_constant(Xs, prepend = True)
Ws = SAL_MUJ[['EDUC', 'EDAD', 'HIJOSMEN', 'TMIMP']] # Variables exógenas ecuación selección
W = sm.add_constant(Ws, prepend = True)
import heckman as heckman   # exec(open("heckman.py").read())
res = heckman.Heckman(lSALARIO, X, W).fit(method='twostep')
print(res.summary()) 
```
