---
title: "Autocorrelación y modelos dinámicos"
author: "J. Ramajo"
date: '2020'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dynlm)
library(car)
library(lmtest)
library(sandwich)
library(orcutt)
#
TIPOS_ESP <- read_csv("TIPOS_ESP.csv")
TIPOS_ESP_ts <- ts(TIPOS_ESP, start=c(1982,1), end = c(1990,3), frequency = 4)
plot(TIPOS_ESP_ts)
#
RL <- TIPOS_ESP_ts[,"RL"]
R3M <- TIPOS_ESP_ts[,"R3M"] 
RD <- TIPOS_ESP_ts[,"RD"]
#
# Modelo de Klein-Monti
#
S(lm_KM <- lm(RL ~ R3M + RD))
#
# Especificación ARDL(0,0,0) - modelo estático- 
#
S(dynlm_KM_0 <- dynlm(RL ~ R3M + RD))
#
# Contrastes de correlación en los errores (autocorrelación)
#
r <-residuals(dynlm_KM_0)
plot(r)
abline(h=0, lty=2)
#
# Correlograma de los residuos
#
corr <- acf(r)
corr$acf[2:10]
#
# Test de Durbin-Watson
#
dwtest(dynlm_KM_0, alternative = "two.sided")
dwtest(dynlm_KM_0, alternative = "greater")
#
# Test de Breusch-Godfrey
#
bgtest(dynlm_KM_0, order=1, type="Chisq", fill=0)
#
# Corrección de la autocorrelación: MCO corregidos, MCG-AR, modelos dinámicos del tipo ARDL
#
# MCO corregidos: errores estándar robustos, HAC (Newey-West)
#
S(dynlm_KM_0 <- dynlm(RL ~ R3M + RD), vcov.=vcovHAC(dynlm_KM_0))
#
# Mínimos cuadrados generalizados (MCG): errores AR(1)
#
cochrane.orcutt(dynlm_KM_0)
#
# Modelo -dinámico ARDL(1,1,1) 
#
S(dynlm_KM_1 <- dynlm(RL ~ L(RL, 1:1) + L(R3M, 0:1) + L(RD, 0:1)))
#
```
