---
title: "Datos financieros: modelos vectoriales autorregresivos, VAR"
author: "J. Ramajo"
date: '2020'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#
library(car)
library(vars)
library(tseries)
library(dynlm)
library(FinTS)
#
load("TIPOS_CAMB.RData")
TIPOS_CAMB_ts <- ts(monedas[,2:7], frequency=365, start=c(1998, 348)) 
plot(TIPOS_CAMB_ts)
#
EurUsd <- TIPOS_CAMB_ts[,"EUR"]
GbpUsd <- TIPOS_CAMB_ts[,"GBP"]
JpyUsd <- TIPOS_CAMB_ts[,"JPY"]
# ts.plot(XUsd, ylab="Tipo de cambio X frente al dólar")
#
rEurUsd <- TIPOS_CAMB_ts[,"reur"]
rGbpUsd <- TIPOS_CAMB_ts[,"rgbp"]
rJpyUsd <- TIPOS_CAMB_ts[,"rjpy"]
# ts.plot(rXUsd, ylab="Variaciones (returns) tipo de cambio X frente al dólar")
#
VARdat <- as.matrix(cbind(rEurUsd,rGbpUsd,rJpyUsd))
#
VARselect(VARdat,lag.max = 7, type = "const") # type = c("const", "trend", "both", "none")
VAR2 <-  VAR(VARdat,p=2)
summary(VAR2)
# Funciones de respuesta al impulso (IRFs)
irf_VAR2 <- irf(VAR2)
plot(irf_VAR2)
# Funciones de descomposición de la varianza del error de predicción (FEVDs)
fevd_VAR2 <- fevd(VAR2)
plot(fevd_VAR2)
# Contrastes de causalidad de Granger
grangertest(rEurUsd ~ rGbpUsd)
grangertest(rEurUsd ~ rJpyUsd)
causality(VAR2,cause = c("rGbpUsd","rJpyUsd"))$Granger
#
grangertest(rGbpUsd ~ rEurUsd)
grangertest(rGbpUsd ~ rJpyUsd)
causality(VAR2,cause = c("rEurUsd","rJpyUsd"))$Granger
#
grangertest(rJpyUsd ~ rEurUsd)
grangertest(rJpyUsd ~ rGbpUsd)
causality(VAR2,cause = c("rEurUsd","rGbpUsd"))$Granger
# Modelización (G)ARCH
hist(rEurUsd, main="", breaks=20, freq=FALSE, col="grey")
hist(rGbpUsd, main="", breaks=20, freq=FALSE, col="grey")
hist(rJpyUsd, main="", breaks=20, freq=FALSE, col="grey")
# Contraste de Engel de efectos ARCH
S(VAR2_rEurUsd <- dynlm(rEurUsd ~ L(rEurUsd,1:2) + L(rGbpUsd,1:2) + L(rJpyUsd,1:2)))
ArchTest(VAR2_rEurUsd$residuals , lags = 1)
#
# Estimación de modelos GARCH para los residuos del modelo
#
summary(garch(VAR2_rEurUsd$residuals,c(0,1)))
#
summary(garch(VAR2_rEurUsd$residuals,c(1,1)))
```
