---
title: "Normalidad y datos atípicos"
author: "J. Ramajo"
date: '2020'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(car)
library(MASS)
library(effects)
library(tidyverse)
library(RcmdrMisc)
library(sfsmisc)
library(quantreg)
library(lmtest)
library(sandwich)
library(dynlm)
library(moments)
library(tseries)
#
ATIP <- read_csv("ATIP.csv")
View(ATIP)
summary(ATIP)
#
# Diagrama de puntos
#
scatterplotMatrix(~ Y + X, id=list(n=3), smooth=list(span=0.7), data=ATIP)
ggplot(ATIP, aes(x=X, y=Y)) + geom_point() + labs(title="Diagrama de puntos", x="X", y="Y")
#
# Modelo de regresión lineal
#
S(lm_YX <- lm(Y ~ X, data = ATIP))
plot(Y ~ X , data=ATIP)
abline(lm_YX)
plot(lm_YX, which = 1:6)
#
# Distribución de los errores del modelo
#
plot(lm_YX$residuals)
hist(lm_YX$residuals, main = "")
box()
densityPlot(residuals(lm_YX))
qqnorm(residuals(lm_YX))
qqPlot(lm_YX, distribution="norm")
#
# Contrastes de normalidad
#
r <- resid(lm_YX)
rbar <- mean(r)
sdr <- sd(r)
hist(lm_YX$residuals, col="grey", freq=FALSE, main="Distribución de los residuos", ylab="Densidad", xlab="Residuos")
curve(dnorm(x, rbar, sdr), col=2, add=TRUE, ylab="Densidad", xlab="r")
#
# Librería moments
skewness(lm_YX$residuals)
kurtosis(lm_YX$residuals)
agostino.test(lm_YX$residuals)
anscombe.test(lm_YX$residuals)
jarque.test(lm_YX$residuals)
# librería tseries
jarque.bera.test(lm_YX$residuals)
shapiro.test(lm_YX$residuals)
#
# Detección de observaciones atípicas
#
# Observaciones atípicas en las variables explicativas (leverages <-> apalancamiento)
#
hat <- hatvalues(lm_YX)
hat
which(hat > 2 * mean(hat))
plot(hat)
abline(h = mean(hat), col = 4)
abline(h = 2 * mean(hat), col = 2)
id <- which(hat > 2 * mean(hat))
text(id, hat[id], rownames(ATIP)[id], pos = 1, xpd = TRUE)
#
# Observaciones atípicas en la variable dependiente (outliers)
#
slm_YX <- summary(lm_YX)
# Residuos estandarizados
r <- lm_YX$residuals/slm_YX$sigma
r
densityPlot(r)
which(abs(r) > 2.5)
plot(r)
abline(h = c(0,-2.5, 2.5), col = 4)
id <- which(abs(r) > 2.5)
text(id, r[id], rownames(ATIP)[id], pos = 1, xpd = TRUE)
# Residuos estudentizados (internamente)
rs <- rstandard(lm_YX)
rs
densityPlot(rs)
which(abs(rs) > 2)
plot(rs)
abline(h = c(0,-2, 2)*sd(rs), col = 4)
id <- which(abs(r) > 2*sd(rs))
text(id, r[id], rownames(ATIP)[id], pos = 1, xpd = TRUE)
# Residuos estudentizados (externamente)
rt <- rstudent(lm_YX)
rt
densityPlot(rt)
qqPlot(lm_YX)
outlierTest(lm_YX)
#
# Diagnósticos
#
# Observaciones influyentes (cálculo de DFBETAS_i, DFFITS_i, COVRATIO_i, DCOOK_i y h_i ; inf -> señalan obs. inusuales para al menos una medida)
#
influence.measures(lm_YX)
S(influence.measures(lm_YX))
influenceIndexPlot(lm_YX, vars=c("Hat", "Studentized","Cook"))
influencePlot(lm_YX, xlab="Hat values")
# Medidas individuales
hat <- hatvalues(lm_YX)
dfbetas <-  dfbetas(lm_YX)
dffits <-  dffits(lm_YX)
dcook <-  cooks.distance(lm_YX)
hat ; dfbetas ; dffits; dcook
#
max(hatvalues(lm_YX))
which.max(hatvalues(lm_YX))
#
max(abs(dffits(lm_YX)))
which.max(abs(dffits(lm_YX)))
#
max(cooks.distance(lm_YX))
which.max(cooks.distance(lm_YX))
#
# Gráficos de variable añadida, buscando casos influyentes
avPlots(lm_YX, id=list(cex=0.60, method="mahal"))
#
# Regresión cuartilítica
#
S(lm_YX <- lm(Y ~ X, data = ATIP))
S(qr_YX <- rq(Y ~ X, data = ATIP)) # tau=0.5
plot(Y ~ X , data=ATIP)
abline(lm_YX)
abline(qr_YX, lty=2)
legend("topleft", c("Regresión MCO", "Regresión MDA"), lty = c(1, 2), bty = "n")
#
# Secuencial
S(qr_YX <- rq(Y ~ X, data = ATIP, tau=seq(0.1,0.9,0.1)))
plot(summary(qr_YX), level=0.95)
# Discreta
S(qr_YX <- rq(Y ~ X, tau = c(0.25, 0.50, 0.75), data = ATIP))
plot(qr_YX)
#
```
