---
title: "Cambio estructural"
author: "J. Ramajo"
date: '2020'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(car)
library(stargazer)
SAL_SEX <- read_csv("SAL_SEX.csv")
View(SAL_SEX)
S(lm_SAL <- lm(log(SALARIO) ~ EDUC + EXPER , data = SAL_SEX))
#
Boxplot(~SALARIO, data=SAL_SEX, main="", ylab="SALARIO")
#
class(SAL_SEX$MUJER)
SEXO <- factor(SAL_SEX$MUJER, labels=c("Hombre", "Mujer"))
summary(SEXO)
Boxplot(SALARIO~SEXO, data=SAL_SEX, id=list(method = "none"))
#
scatterplot(SALARIO ~ EDUC| SEXO, data=SAL_SEX, smooth=FALSE, boxplots=FALSE, ylab="Relación Salario/Educación")
scatterplot(SALARIO ~ EXPER| SEXO, data=SAL_SEX, smooth=FALSE, boxplots=FALSE, ylab="Relación Salario/Experiencia")
#
SAL_SEX_h <- SAL_SEX[which(SAL_SEX$MUJER==0),] #hombres
SAL_SEX_m <- SAL_SEX[which(SAL_SEX$MUJER==1),] #mujeres

S(lm_SAL_h <- lm(log(SALARIO) ~ EDUC + EXPER , data = SAL_SEX_h))
S(lm_SAL_m <- lm(log(SALARIO) ~ EDUC + EXPER , data = SAL_SEX_m))
#
# Test de Chow
S(lm_SAL_int <- lm(log(SALARIO) ~ EDUC + EXPER + MUJER/(EDUC + EXPER) , data = SAL_SEX))
anova(lm_SAL, lm_SAL_int)
#
compareCoefs(lm_SAL, lm_SAL_h, lm_SAL_m)
#
```
