---
title: 'Configuración de R y Python en RStudio'
author:
  name: Julián Ramajo, ramajo@unex.es
  affiliation: GRADO EN ESTADÍSTICA | ECONOMETRIA (502243)
subtitle: 'Aplicación 0.0.b: Software y librerías instaladas'
output:
  html_document:
    theme: journal
    highlight: haddock
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

# Versiones de R y Python instaladas

## R

```{r}
print(R.version.string)
```

## Python

```{python}
import sys
print(sys.version)
```

# Librerías de R y Python instaladas

## R

```{r}
installed_packages <- installed.packages()[, c("Package", "Version", "License", "NeedsCompilation", "Built")]
installed_packages_list <- apply(installed_packages[, c("Package", "Version")], 1, function(x){paste0(x[1], "==", x[2])})
cat(paste0(sort(installed_packages_list), sep = "\n"))
```

## Python

```{python}
import pkg_resources
installed_packages = pkg_resources.working_set
installed_packages_list = sorted(["%s==%s" % (i.key, i.version) for i in installed_packages])
print("\n".join(installed_packages_list))
```
