---
title: 'TEMA 1: INTRODUCCIÓN A LA ECONOMETRÍA'
author:
  name: Julián Ramajo, ramajo@unex.es
  affiliation: GRADO EN ESTADÍSTICA | ECONOMETRIA (502243)
subtitle: 'Aplicación 1.1 (Datos de corte transversal): Demanda familiar de carne'
output:
  html_document:
    theme: journal
    highlight: haddock
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

# Introducción

En esta aplicación se estimará una función de demanda estándar con datos micro sobre 30 familias americanas:

$$Q = \beta_0 + \beta_1P + \beta_2Y + e$$

# Código R

```{r}
# Lectura de librerías
library(tidyverse)
library(GGally)
library(skimr)
library(coefplot)
library(report)
# Lectura de datos 
DEM_CARNE <- read_csv("DEM_CARNE.csv")
#
dim(DEM_CARNE)
str(DEM_CARNE)
head(DEM_CARNE)
tail(DEM_CARNE)
# Análisis exploratorio (EDA)
summary(DEM_CARNE)
report(DEM_CARNE)
skim(DEM_CARNE)
# Gráficas parciales
GGally::ggpairs(DEM_CARNE)
#
ggplot(DEM_CARNE, aes(x = P, y = Q)) +
  geom_point(color = "blue") +
  geom_jitter(color = "blue") +
  geom_function(fun = function(x) {y = mean(DEM_CARNE$Q)}, linetype = "dotdash") +
  geom_smooth(method='lm', formula = y~x, se = FALSE, color = "red", linetype = "dashed") +
  xlab("P (precio)") +
  ylab("Q (cantidad)") +
  theme_minimal()
ggplot(DEM_CARNE, aes(x = Y, y = Q)) +
  geom_point(color = "blue") +
  geom_jitter(color = "blue") +
  geom_function(fun = function(x) {y = mean(DEM_CARNE$Q)}, linetype = "dotdash") +
  geom_smooth(method='lm', formula = y~x, se = FALSE, color = "red", linetype = "dashed") +
  xlab("Y (renta)") +
  ylab("Q (cantidad)") +
  theme_minimal()
# Regresión MCO
DEM_model <- lm(formula = Q ~ P + Y, data = DEM_CARNE)
summary(DEM_model)
report(DEM_model)
```

## Visualización 3D de los datos y del plano ajustado del modelo

```{r}
library(plotly)
library(magrittr)
#  
model <- lm(Q ~ P + Y, data = DEM_CARNE)  
plot_ly(data = DEM_CARNE) %>%
    add_trace(x = ~P, y = ~Y, z = ~Q, mode = "markers", type = "scatter3d",
              marker = list(size = 5, color = "blue", symbol = 104), name = "Observaciones") %>% 
    add_trace(z = model$fitted.values, x = ~P, y = ~Y, type = "mesh3d", 
              name = "Valores ajustados") %>%
    layout(scene = list(xaxis = list(title = 'P'), yaxis = list(title = 'Y'),
                        camera = list(eye = list(x = -1.5, y = 1.5, z = 0)),
                        zaxis = list(title = 'Q'), aspectmode='cube')) 
```

# Código Python

```{python}
import pandas as pd
import statsmodels.formula.api as smf
# Lectura de datos
DEM_CARNE = pd.read_csv("DEM_CARNE.csv")
# Análisis exploratorio (EDA)
DEM_CARNE.describe()
# Regresión MCO
model = smf.ols(formula = "Q ~ P + Y", data = DEM_CARNE)
DEM_model = model.fit()
print(DEM_model.summary())
```

# Código Julia

```{r, echo = FALSE}
# Ejecutar siempre que se vaya a usar Julia en RStudio
library(JuliaCall)
julia <- julia_setup()
```

```{julia, message = FALSE, warning = FALSE}
using DataFrames, CSV, GLM;
# Lectura de datos
DEM_CARNE = CSV.read("DEM_CARNE.csv", DataFrame);
#
size(DEM_CARNE)
names(DEM_CARNE)
show(first(DEM_CARNE,6))
show(last(DEM_CARNE,6))
# Análisis exploratorio (EDA)
show(describe(DEM_CARNE))
# Regresión MCO (librería GLM)
DEM_model = lm(@formula(Q ~ P + Y), DEM_CARNE)
# R^2
print("R^2 estándar ->   ",r2(DEM_model))
# Regresión MCO (librería Econometrics)
using Econometrics;
DEM_model_2 = fit(EconometricModel, @formula(Q ~ P + Y), DEM_CARNE)
```

