---
output:
  html_document: default
  pdf_document: default
---

## Lectura de datos y EDA

```{r}
library(tidyverse)
library(ggplot2)
library(GGally)

datos <- read_csv("DEM_CARNE.csv")
head(datos)
str(datos)
summary(datos)
```

## Gráficas parciales

```{r}
GGally::ggpairs(datos)

ggplot(datos, aes(x = P, y = Q)) +
  geom_point(color = "blue") +
  geom_jitter(color = "blue") +
  geom_function(fun = function(x) {y = mean(datos$Q)}, linetype = "dotdash") +
  geom_smooth(method='lm', formula = y~x, se = FALSE, color = "red", linetype = "dashed") +
  xlab("P (precio)") +
  ylab("Q (cantidad)") +
  theme_minimal()

ggplot(datos, aes(x = Y, y = Q)) +
  geom_point(color = "blue") +
  geom_jitter(color = "blue") +
  geom_function(fun = function(x) {y = mean(datos$Q)}, linetype = "dotdash") +
  geom_smooth(method='lm', formula = y~x, se = FALSE, color = "red", linetype = "dashed") +
  xlab("Y (renta)") +
  ylab("Q (cantidad)") +
  theme_minimal()
```

## Regresión MCO
$$Q = \beta_0 + \beta_1P + \beta_2Q + e$$

### Con R

```{r}
model <- lm(data = datos, formula = Q ~ P + Y)
summary(model)
```

### Con Python

```{python}
import pandas as pd
import statsmodels.formula.api as smf

datos = pd.read_csv("DEM_CARNE.csv")
model = smf.ols(formula = "Q ~ P + Y", data = datos)
dem_model = model.fit()
print(dem_model.summary())
```

## Visualización 3D de los datos y del plano ajustado del modelo

```{r}
  library(plotly)
  library(magrittr)
  
model <- lm(data = datos, formula = Q ~ P + Y)  
plot_ly(data = datos) %>%
    add_trace(x = ~P, y = ~Y, z = ~Q, mode = "markers", type = "scatter3d",
              marker = list(size = 5, color = "blue", symbol = 104), name = "Observaciones") %>% 
    add_trace(z = model$fitted.values, x = ~P, y = ~Y, type = "mesh3d", 
              name = "Valores ajustados") %>%
    layout(scene = list(xaxis = list(title = 'P'), yaxis = list(title = 'Y'),
                        camera = list(eye = list(x = -1.5, y = 1.5, z = 0)),
                        zaxis = list(title = 'Q'), aspectmode='cube')) 
```
