---
title: "Datos financieros: modelos ARCH/GARCH y generalizaciones"
author: "J. Ramajo"
date: '2020'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("AER")
library("tseries")
library("ggplot2")
library("imputeTS")
library("fGarch")
#
# EURUSD <- get.hist.quote("EURUSD=X", start = "2004-01-01", end = "2020-06-30")
# plot(EURUSD)
# autoplot(EURUSD$Close) + facet_free()
# statsNA(EURUSD$Close)
# EurUsd <-  na.approx(EURUSD$Close)
# autoplot(cbind(EURUSD$Close, EurUsd)) + facet_free()
# write.zoo(EurUsd, "FIN_EURUSD.CSV", index.name = "Index")
#
EurUsd <- read.zoo("FIN_EURUSD.CSV", header = FALSE, sep = " ", format = "%Y-%m-%d")
plot(EurUsd)
class(EurUsd)
plotNA.distributionBar(EurUsd, breaks = 20)
statsNA(EurUsd)
autoplot(EurUsd) + facet_free()
rEurUsd <- 100 * diff(log(EurUsd))
statsNA(rEurUsd)
autoplot(rEurUsd) + facet_free()
summary(rEurUsd)
#
rEurUsd_GARCH <- garchFit(~ garch(1,1), data = rEurUsd, cond.dist = "norm", trace = FALSE)
summary(rEurUsd_GARCH)
plot(rEurUsd_GARCH, which = 3)
#
# Plot selection: 
# 1:   Time Series                                 2:   Conditional SD                           
# 3:   Series with 2 Conditional SD Superimposed   4:   ACF of Observations                      
# 5:   ACF of Squared Observations                 6:   Cross Correlation                        
# 7:   Residuals                                   8:   Conditional SDs                          
# 9:   Standardized Residuals                     10:   ACF of Standardized Residuals            
# 11:   ACF of Squared Standardized Residuals      12:   Cross Correlation between r^2 and r      
# 13:   QQ-Plot of Standardized Residuals    
#
rEurUsd_ARMA_GARCH <- garchFit(~ arma(1,0) + garch(1,1), data = rEurUsd, trace = FALSE)
summary(rEurUsd_ARMA_GARCH)
#
rEurUsd_ARMA_APARCH <- garchFit(~ arma(1,0) + aparch(1,1), data = rEurUsd, trace = FALSE)
summary(rEurUsd_ARMA_APARCH)
```
