---
title: "Aplicación 2.4: La apertura de un nuevo negocio en Pekín"
author: "J. Ramajo"
date: '2020'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This R Markdown file reproduces the data analysis described in Section 1.5 of _An R Companion to Applied Linear Regression, 3rd Edition_.  See the text for further explanation.

# Preliminares

Lectura de packages
```{r}
library(readr)
library(car)
library(MASS)
library(effects)
library(tidyverse)
```

Lectura de datos

```{r}
VENT_HAMB <- read_csv("VENT_HAMB.csv")
VENT_HAMB_ts <- ts(VENT_HAMB, start=c(1), end = c(20), frequency = 1)
Q <- VENT_HAMB_ts[,"Q"]
P <- VENT_HAMB_ts[,"P"]
A <- VENT_HAMB_ts[,"A"]
plot(VENT_HAMB_ts)
```

Gráficas

```{r fig.height=8, fig.width=8}
#
scatterplot(Q ~ P, pch=".")
scatterplot(Q ~ A)
#
ggplot(VENT_HAMB, aes(x=P, y=Q)) + geom_point() + labs(title="Diagrama de puntos", x="Precio", y="Ventas")
ggplot(VENT_HAMB, aes(x=A, y=Q)) + geom_point() + labs(title="Diagrama de puntos", x="Publicidad", y="Ventas")
#
scatterplotMatrix( ~ Q + P + A, id=list(n=3), data=VENT_HAMB)
```

## Análisis econométrico

```{r}
lm_VENTAS <- lm(Q ~ P + A)
summary(lm_VENTAS)
#
lm_VENTAS_poly <- lm(Q ~ P + poly(A,2, raw=TRUE))
# lm_VENTAS_poly <- lm(Q ~ P + A + I(A^2))
summary(lm_VENTAS_poly)
plot(Effect("P", lm_VENTAS_poly))
plot(Effect("A", lm_VENTAS_poly))
#
# Efectos marginales
#
b <- coef(lm_VENTAS_poly)
b
dQdP <- b[2]
dQdP
dQdA <- b[3] + 2*b[4]*A
dQdA
scatterplot(dQdA ~ A)
#
# Predicciones
new_P_A <- data.frame(P = c(5.25, 5.30, 5.40, 5.50 , 5.60), A = c(200, 210, 220, 230 , 240))
new_P_A
predict(lm_VENTAS_poly, new_P_A, interval = "prediction")
```