---
title: Consumo privado en Estados Unidos
subtitle: Ejemplo de estimación conjunta en R y Python
author:
  name: Julián Ramajo
  affiliation: Universidad de Extremadura | ECONOMETRIA (502243)
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    keep_md: false
    theme: journal
    highlight: haddock
    toc: yes
    toc_depth: 2
    toc_float: yes
always_allow_html: true
urlcolor: blue
mainfont: cochineal
sansfont: Fira Sans
monofont: Fira Code 
knit: (function(inputFile, encoding) {
 rmarkdown::render(inputFile, encoding = encoding, 
 output_format = 'all') 
 })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, dpi=300)
```

## Nota teórica

La función de consumo Keynesiana. Estimación MCO con R y Python

### Resultados multi-columna


:::::: {.columns}
::: {.column width="49%" data-latex="{0.49\textwidth}"}

Resultados con el código **R** code.

```{r, message=FALSE}
#
library(tidyverse)
CONS_USA <- read_csv("CONS_USA.csv")
#
ts_CONS_USA <- ts(CONS_USA[,2:3], start=c(1959), end = c(2015))
head(ts_CONS_USA)

CONS_USA %>%
  ggplot(aes(x = Y, y = C)) +
  geom_point() +
  ylab("Consumo privado ($ million)") + xlab("Renta disponible ($ million)")
#
KEYNES_model <- lm (C ~ Y, data = ts_CONS_USA)
summary(KEYNES_model)    
```
:::

::: {.column width="2%" data-latex="{0.02\textwidth}"}

:::

::: {.column width="49%" data-latex="{0.49\textwidth}"}

Y el equivalente en **Python**.

```{python, message=FALSE}
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
#
CONS_USA = pd.read_csv("CONS_USA.csv", index_col=0)
CONS_USA.head()
plt.style.use('seaborn')
CONS_USA.plot(x='Y', y='C', kind='scatter')
plt.show()
#
model = smf.ols(formula = "C ~ Y", data = CONS_USA)
KEYNES_model = model.fit()
print(KEYNES_model.summary())   
```
:::
::::::
\ <!-- an empty Div again to give some extra space before the next block -->
